language: c
sudo: false

branches:
  only:
    - master

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-5
    - gcc-6

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-5
  - os: linux
    compiler: gcc-6

script:
  - make && ./phonebook_orig && ./phonebook_opt
  - make clean && make DEBUG=1 && ./phonebook_orig && ./phonebook_opt